apiVersion: v2
name: nginx
description: A plain nginx
type: application
version: 0.2.2
appVersion: "1.21.0"
icon: https://upload.wikimedia.org/wikipedia/commons/c/c5/Nginx_logo.svg
maintainers:
  - name: Rancher
    url: https://github.com/rancher
