default_password: admin
rancher_version: v2.1.6
cluster_name: rodeo
rodeo: true
docker_version:
  server: "17.03"
  node: "17.03"
server:
  cpus: 1
  memory: 2000
node:
  count: 1
  cpus: 2
  memory: 3000
ip:
  server: 172.22.101.101
  node:   172.22.101.111
linked_clones: true
net:
  private_nic_type: 82545EM
  network_type: private_network
roles:
  node-01: all
